name: Publish

on:
  release:
    types: [published]

concurrency:
  group: npm-publish
  cancel-in-progress: false

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Validate
        run: yarn validate

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
